server:
  port: 1010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_bank
    username: postgres
    password: bahman1234


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

